spring:
  messages:
    encoding: iso-8859-1
  profiles:
    active:
      - base
      - dev
  config:
    location:
      - classpath:/resources/config/application-base.yaml
      - classpath:/resources/config/application-dev.yaml
