### Create new user - expects successful registration - Status 200
POST http://localhost:8080/api/v1/users/account-registration
Content-Type: application/json
Accept-Language: es_ES

{
  "username": "Deno",
  "password": "SomeEpicPassword",
  "email": "santiagozapataposada7@gmail.com"
}

### Create new user - expects binding failure - Status 400
POST http://localhost:8080/api/v1/users/account-registration
Content-Type: application/json
Accept-Language: es_ES

{
  "username": "",
  "password": "",
  "email": ""
}
