name: CI pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  code-linting:
    runs-on: ubuntu-latest
    name: Code linting
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: corretto
          java-version: 17
      - name: Check PMD rules
        run: ./gradlew pmdMain pmdTest
      - name: Checkstyle rules
        if: success() || failure()
        run: ./gradlew checkstyleMain checkstyleTest

  security-scan:
    runs-on: ubuntu-latest
    name: Code vulnerability scan
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: corretto
          java-version: 17
      - name: Vulnerability scan
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
      - name: Upload vulnerability scan sarif file
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

  tests:
    needs:
      - security-scan
      - code-linting
    runs-on: ubuntu-latest
    name: Execute all tests
    steps:
      - name: Checkout Github repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          cache: gradle
          distribution: corretto
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run tests with Gradle
        run: ./gradlew test
