name: CI pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Grype security scan

  test:
    runs-on: ubuntu-latest
    name: Execute all tests
    steps:
      - name: Checkout Github repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: 'corretto'
          java-version: '17'
      - name: Run tests
        run: ./gradlew test
